version: "3.9"
services:
  api:
    build: ./django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_backend:/code/django_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: