# Generated by Django 4.0.4 on 2022-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alignment',
            old_name='alignment_run',
            new_name='alignment_run_fk',
        ),
        migrations.AlterField(
            model_name='alignment',
            name='matched_fragment',
            field=models.TextField(verbose_name='Matched Fragment'),
        ),
    ]
