version: "3.9"
services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/django_backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    build: .
    command: python ./worker/run.py
    volumes:
      - .:/code/worker
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: